### ISSUE TITLE
brecq errors

### ISSUE THREAD

**Issue by bruce1408** [ModelTC/Dipoorlet#34]
When I use adaround algorithm for quantization, then it reports an error. This is why.

```
Traceback (most recent call last):
  File "/mnt/miniforge3/envs/torch113_cuda116/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/miniforge3/envs/torch113_cuda116/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/Dipoorlet/dipoorlet/__main__.py", line 151, in <module>
    weight_calibration(onnx_graph, act_clip_val, weight_clip_val, args)
  File "/mnt/Dipoorlet/dipoorlet/weight_transform/weight_trans_base.py", line 57, in weight_calibration
    graph_after_wt = adaround(onnx_graph, graph_after_wt, act_clip_val, weight_clip_val, args)
  File "/mnt/Dipoorlet/dipoorlet/weight_transform/adaround.py", line 115, in adaround
    round_mask = learning_round_mask(
  File "/mnt/Dipoorlet/dipoorlet/weight_transform/adaround.py", line 152, in learning_round_mask
    loss = L2_norm(output, fp_output) + reg(ada_layer.module.round_mask, cur_iter)
  File "/mnt/Dipoorlet/dipoorlet/weight_transform/ada_quant_layer.py", line 117, in L2_norm
    return (pred - tgt).pow(2.0).sum(1).mean()
RuntimeError: The size of tensor a (360) must match the size of tensor b (368) at non-singleton dimension 2
```

**Comment by gushiqiao** [comment]
Try using onnx.shape_inference(model) to see if it works?
